### ISSUE TITLE
improve data handling

### ISSUE THREAD

**Issue by wbarfuss** [wbarfuss/modelingframework#1]
how single runs get stored gets too slow for a large number of files - essentially because of globing.
-> change the data management to perhaps something like [pandas hdf5 pytables](http://pandas-docs.github.io/pandas-docs-travis/io.html#hdf5-pytables)

Be aware of parallel  processes writing model results!

Further Links
- http://stackoverflow.com/questions/14262433/large-data-work-flows-using-pandas#14268804
- http://pandas-docs.github.io/pandas-docs-travis/io.html#multiple-table-queries
- http://pandas-docs.github.io/pandas-docs-travis/io.html#iterating-through-files-chunk-by-chunk

**Comment by wbarfuss** [comment]
Especially the resaving could benefit with a significant speed up, since the `glob`ing takes a lot of time!!!

**Comment by jakobkolb** [comment]
A lot of this seems to be addressed in the current pull request of Wb_data_iss1. With some small refinements, this can be considered done in my opinion.
Once this is merged, we should consider another release, since downward compatibility will be broken.
