### ISSUE TITLE
INDEX

### ISSUE THREAD

**Issue by wbarfuss** [wbarfuss/modelingframework#13]
I have the strong suspicion that the `index` causes some troubles.
It say in in the docs  
```
        index : dict
            indicating the varied Parameters as
            {position in parameter_combinations: name}
            is needed for post processing to create the
            multi index containing the variable Parameters
```
but the code (experiment_handling.py l103-106 )
```
        self.kwparameter_combinations = \
            [{index[i]: params[i]
              for i in range(min(len(params), len(index.keys())))}
             for params in parameter_combinations]
```
assumes that `i` starts with `0`. However, the first varying parameter could be not the first one, right?

Second: As far is I understand correctly, the index is needed for the resaving routing. So I suggest to give the index to the resaving routine as a parameter - instand of an object parameter.

**Comment by jakobkolb** [comment]
Hmm.. so far, the index dictionary did not cause me any trouble. But that might be because the parameters that I listed there were indeed only those that I actually varied. All others, I specified as keyword parameters with default values in the interface of the run_function of the experiment.

I assume, something like 
```
self.kwparameter_combinations = \
            [{index[i]: params[index[i]]
              for i in range(min(len(params), len(index.keys())))}
             for params in parameter_combinations]
```
would make it work in more general cases (also supplying non-varied parameter values in the parameter combination tuple)?

**Comment by wbarfuss** [comment]
(TEST)
in your suggestion `i` still starts at `0`. I'll get back to this later when I have more time

**Comment by jakobkolb** [comment]
I don't understand the Issue with i starting at 0 as long as parameter combinations only consist of parameters that are actually varied and the index dictionary is of the form
```
index = {0: 'name of 1st paramter in index', ..., n: 'name of n+1st paramter in index'}
```
After a second look I changed the expression to 
```
        self.kwparameter_combinations = \
            [{index[i]: params[i]
              for i in index.keys()}
             for params in parameter_combinations]
```
though. This should also cover the general case of having fixed and varied parameters in the parameter combinations and then picking them out.

**Comment by jakobkolb** [comment]
Will test this and push to master, if it proves to be stable.

**Comment by wbarfuss** [comment]
Looks good, thumps up. I thought of something like this as well.
