### ISSUE TITLE
improve parallel processing

### ISSUE THREAD

**Issue by wbarfuss** [wbarfuss/modelingframework#2]
right now the why runs get parallelized is a terrible hack. 
-> rewrite 'experiment_handling.py' to depend directly on mpi4py

**Comment by jakobkolb** [comment]
until now, only the compute function relies on mpi4py. As a consequence, if an experiment is run in a parallel environment, all other functions (resave plot etc.) are run in parallel without any use - corrupting log files, wasting wall time and and in the worst case messing with the output.

This is urgent.

**Comment by jakobkolb** [comment]
Proposed improvements in #7

**Comment by wbarfuss** [comment]
opened an issue for the parameter combinations that don't terminate (#8)
