### ISSUE TITLE
Error in .resave using pandas 1.5.2

### ISSUE THREAD

**Issue by zugnachpankow** [wbarfuss/modelingframework#21]
Hey!

Using the current version 1.5.2 of pandas with pymofa i run into some errores trying to apply the experiment_handling.resave method, that i assume to be caused mainly by changes in new pandas versions.

![image](https://user-images.githubusercontent.com/64842372/210223349-28e32678-af28-40d5-b9c4-a4aea31d2d9d.png) 
Can be fixed by replacing `pd.core.index.MultiIndex` with `pd.MultiIndex`.

![image](https://user-images.githubusercontent.com/64842372/210223557-ab401285-b088-4a04-929e-9a65c14f7b1f.png) 
Can be fixed by replacing `labels=` and method `.labels` by `codes=` and `.codes`, respectively.

Having applied the named fixes everything seems to run as expected. Maybe it is possible to double check this? Many thanks in advance.

Kind regards,
Max

**Comment by wbarfuss** [comment]
Thanks. I haven't used this for years, so it likely contains breaking changes with newer versions of, e.g., pandas.

Your solution looks great to me. Could you make a pull request? Or, if you plan to use pymofa more often, do you want to maintain the repository?

**Comment by zugnachpankow** [comment]
Hey, I just made a pull request, hope everything is fine with it. I plan to use pymofa for the remainder of my thesis with copan (approx. 3 months). I will talk with Jonathan about this and get back to you.

**Comment by wbarfuss** [comment]
Thanks a lot. Sounds good! Let me know.
